server:
    timezone: Europe/Brussels
    locale: nl_NL.UTF-8
    packages: [git, imagemagick, vim, pkg-config, libssl-dev, libsslcommon2-dev]
vagrant_local:
    vm: { base_box: trusty64, hostname: cmsms.app, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    docroot: /vagrant/cms
php7:
    extensions: [php7.0-intl, php7.0-json, php7.0-mbstring, php7.0-readline, php7.0-tidy, php7.0-xml, php7.0-zip, php7.0-curl, php7.0-gd, php7.0-mysql]
    logdir: /vagrant/logs
    pecl: []
mysql:
    root_password: cmsms
    database: cmsms
    user: cmsms
    password: cmsms
    dump: ''